version: "v2.39.1-desktop.1"

services:
  zookeeper:
    image: zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/microserv"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/microserv"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
